### ISSUE TITLE
High default slippage tolerance

### ISSUE THREAD

**Issue by kitty-the-kat** [groLabs/GSquared#4]
The value `(PERCENTAGE_DECIMAL_FACTOR - baseSlippage) / PERCENTAGE_DECIMAL_FACTOR` is the slippage tolerance for metapool deposits and withdrawals in `invest()` and `divest()`. The default value for this tolerance is unnecessarily large and likely due to a mistake in the decimal arithmetic. Fortunately `baseSlippage` can be fixed by the owner to correct similar errors in the future, but a better default value should be considered.

#### Technical Details

The default value of `PERCENTAGE_DECIMAL_FACTOR` if 1E4 while `baseSlippage` is 50. This means the default tolerance is (10000 - 50) / 10000 = 9950 / 10000 = 99.5%, allowing for 0.5% slippage, in [`invest()`](https://github.com/groLabs/GSquared-foundry/blob/f1831bdb353d4a0b3a8937087e1663f73b75e905/src/strategy/ConvexStrategy.sol#L895) and [`divest()`](https://github.com/groLabs/GSquared-foundry/blob/f1831bdb353d4a0b3a8937087e1663f73b75e905/src/strategy/ConvexStrategy.sol#L825). When the Frax metapool was examined at the time of this review, the Curve Finance frontend estimated a 0.03% slippage if withdrawing 1E8 LP tokens, which was over 20% of the total supply of the metapool. Similarly, when estimating the slippage for a deposit of 1E8 CRV tokens, which would increase the existing balance of CRV in the metapool by over 50%, the frontend estimated a 0.06% slippage.

![Curve metapool frontend withdrawal slippage estimate](./slippage-withdrawal.png)

![Curve metapool frontend deposit slippage estimate](./slippage-deposit.png)

Given the size of the slippage with such large deposits or withdrawals, and considering that the default slippage tolerance on the Curve frontend for this Frax metapool is 0.1%, the existing combination of `PERCENTAGE_DECIMAL_FACTOR` and `baseSlippage` provides too large of a slippage tolerance.

#### Impact

Medium. A large default slippage tolerance could lead to loss of value.

#### Recommendation

Change the default value of `baseSlippage` to 10 or less. Most likely a `baseSlippage` value of 5 would suffice for normal operating conditions and deposit/withdrawal sizes. The root cause could be a typo in `PERCENTAGE_DECIMAL_FACTOR` that should be 1E5 (not 1E4) or a typo in `baseSlippage` that should be 5 (not 50).

**Comment by engn33r** [comment]
> Challenged - Would change to low or informational. 

Agree with @kitty-the-kat on the basis of harvests running through MEV and likelihood of an attack, I will move this to low and update the report

> Reasoning - Base slippage depends on the underlying pool, 50 BP is the same base that Curve uses

When I navigate to [the Frax metapool in the Curve frontend](https://curve.fi/#/ethereum/pools/frax/deposit), the default slippage tolerance is 0.03%. I can manually change the slippage tolerance to one of the other preset options, 0.5% of 1%, but the default is lower.
